sudo: required

services:
  - docker
  
# when tests will work
#language: ruby
#rvm:
#  - 2.3

script:
  - export REPO=scalarm/scalarm_workers_manager
  - docker build . -f Dockerfile -t $REPO 
 

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS	
  - docker tag $REPO $REPO:$TRAVIS_TAG

deploy:
  - provider: script
    script:
      docker push $REPO 
    on:
      branch: master
      tags: true

env:
  global:
    - secure: "HxqAslatmhx3V1gtlVZR/M+D1AuutyuUSyeP7Fuscp1sy0zeFnSnOQCvd2Eu+cc5UNq/0kHciQBgPkjupP6pxiPxAuaKnjCbA87ANhbMmSDDiPuzz0cQJu+mDB2KjbaLYbgrHe0V0apXmc8O6o2pmDSyP66Jnf4pnUc+eISE1ms46a9rh2osbar2sbnx0jhuybuIzxnrR2iVef3qgPHkSQa/t6pZ9IOYstNnJO9/K+oFChl8j8DkibpuRgv8om1narb2OaEkbnAp/oV2N/8NvKcFrP1oxsHRd3+4IrNqsllCpphX63PTxusmdpzs1rQrrr/dknCsyOPIqj4bcTrlChf83hml88prKi4qcseD+YVgAJ6ywIn+TkXMjv91w0f9EEOrmSMIA0uRDQB80CW8v0Nm0bwGPfBzII23ASD8fHN9OpNO9HJw+v/UU1KsKCATFvkxDUAGBhnhWv+/i+p5KTMBldKpKDk0mTjgnDhdvtKQN5CIrHC89zT5+PMr31YaVOpQbErXGcRQb19W8OAVOVCuBF8SxrO0/5Y2ktNWmq5hkHQnCgNJilU7eOQSN8PRv0SUO8yX+PIMVHg9hfW5zYxBpHbNUQmJNqy7h6AFm4wQKpJDqFToJKzSnZBgg3vuFWegYRtsc5tuYaGwro38M2O9S5Bh8q7zokWILRfNfjQ="
    - secure: "PtTEBamgEevk6M/U1vXuMqbUPb1/UNhenthJnRv+Ql4YmlNOrJLM4AdEAgn+64KydUkqsahXRdudlUy5AzMbt7Pq+1wBP16Y91W3yUkWCajlVF90Co7+nEgqEij054mmc8CsgC23Ta5Rz17eSLOYRN31TP/qf8Iam5TnUZIxgD1lW9BiFOoE9FG3xCy980VNKLuth2JdrDnswHf+1RRTOGSo8DKSHgv3IililJs3uPz+WpLDox4UC0nZRT/S9j+NU+iAN2JwXPYif7KKw5tatWrAM6z+L+lGfpMcXaWWPmRNOHOSb3Sc2MkS84hZWRJaiVCl+J2xSv115q0ptigESV3hNaB/a2CUc5zq3bNbpBg/YR7IR9iTL5tNc041CZq+OIu91f/Uth3uu78LHSqWJiEBuU5t3X3S4MZM1iy2YAzTgt8CYN7QNcTQUmpuUr8DED0ng3qxbUU+X5XBDrvi6ct3L6Sn0cqcU0kleIK8ksQZ+GNHEWhS8KW1GH4SW0YoHvFIQmyhqmb6kByJV84lvdgJ6aHiZjvkznEaeYf6BlpSFqxQLgBYbYDGelwbe/OfcuBcpc/u7JmxelndnTgfypa5uEDMXOmNaasOqh2twY/wQpSVw0YvYZS9HK6l9kXz+n64zoO8P9nsbB+wxMQfOY0MrKmOR6Kye7s4uyWCMNs="

