sudo: required

services:
  - docker
  
# when tests will work
#language: go
#go:
#- x.x.x #current go version

script:
  - export REPO=scalarm/scalarm_workers_manager
  - docker build . -f Dockerfile -t $REPO 
 

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS	
  - docker tag $REPO $REPO:$TRAVIS_TAG

deploy:
  - provider: script
    script:
      docker push $REPO 
    on:
      branch: master
      tags: true

env:
  global:
    - secure: "XbLl46JOfBy12XzZTaZ6A+bRl33957iemQWFC4kkVyeAup0KggmkIYfA4SGpFn+q+9/bCa5ubnkIm0qhlvWGA1dr8ZVTiZLjNDGDdiFO1WSoq325O6kobplOheAzdjFuQ514d6GjlHoihkDui+JgMb3aUQ3Q7o5UB3/GrgVyNYQYFchfIz01ETbop0Kt53SqgsetrVGeetJDfm6j82dSzv4ID9fb5LAGLR0xidOMSpKg+lP81CVlx7KPYZV0ndJ9xvxpbynQ0xPjmLr743GooQnFiDfhRTtHz0bDumc/ogd8nEsbzWcu592+zGDLydWKgTk9E26We2Bjygl9+bf05snvbRd1C8G1wAPvHjn2vTbJlufG8GbGNELJHOD0kuj7CTOVaj9/NT4FS3dpk0YGSSpnik18qP+UmES7mY3cxQWXDzn90ywtlNgK90P+3g10VVoQRi8Y5MeQIO+kdMhjtYzCFNjvuKrWmWWmlwcAFKdooU0UpSZDvq81N8XzSHbtS6l/vIwxsQzYCCVLe8lE6mPOkf5SWtEvaNBxn7qLj9uH4GX/F8Jf5d9ZMT51/8oHzoDfjo7Iy7OeDf09XV4Oe/e0SR3QCR13Xll0wiIlp4Was4M3gm65CQckFLUKeIquUu3SrJGgPaRWabb82u32JOES880GQ/2QZ7TPXzJmlWo="
    - secure: "V+x/DMod3jemBKnw6jbTw2ylQL1igUso9B+Er9ImNp1FxaPUD2z2uvyImDil+6J9O1TFgNEXo3ZF51SRji5MfO0ZOCCK7hgDdiKYJU7PxaIaIwMTutzhnvI2dwBtz/k05NwCLTI/yGpSBfk8fnpeZmTL1uVaGdm+cdTkma+D4UhMUCRUTwx2ZbUY+4f0pKFG6LfyXetE7ZWiCID0oc4LCBi0W999IdZR/JHDSTPAhBA0Rxn+fimWNb7WcB4pqhzkLUMRLgPL7atRLyi6/M/D9IGsO/upZQHMrhhmv0TqLSHtU45JS4c9/hyIQlsB728UwmaLJBLcfqagptC4CZfubbEkPHPOJz4wOk/rimo87Z5gYZrgCf3pJ1alvmWrbmi4mSedwweS+Ctl/tGdyWpYC13YCVQR/3pSO1XUqnb3fQYwNGnFfP0FTkaemsJ2EysneXckGccRNPuQh3+v42b9a7HYQ9XOCtpjotjSKpgC5PPjAF+nL9CFX9zltiwSzmpX9tJeWFM5Zt3wIMU8xcnh9cchi4YTDsNhUT8vB8eG+tinj4irXwSm/HzK9rxia9vdL+X7qCo9UIxG5yeUJvy4AgJTm/oVQTW12t2YzSFA9EYroFvrD1pYnbGKlz0ugYNf/IT1V/TC+dVaQzlZOclqjlDWFU0LTk/4kg4h/ltLUAM="
  
